/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'espUltrasonic.name': 'Ultrasonic',
            'espUltrasonic.description': 'Standard ultrasonic distance measurement module.'
        },
        'ru': {
            'espUltrasonic.name': 'Ultrasonic',
            'espUltrasonic.description': 'Standard ultrasonic distance measurement module.'
        },
        'zh-cn': {
            'espUltrasonic.name': 'Ultrasonic',
            'espUltrasonic.description': 'Standard ultrasonic distance measurement module.'
        },
        'zh-tw': {
            'espUltrasonic.name': 'Ultrasonic',
            'espUltrasonic.description': 'Standard ultrasonic distance measurement module.'
        }
    },
    'extensions': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    },
    'blocks': {
        'en': {
            'ULTRASONIC_CATEGORY': 'Ultrasonic',
            'ULTRASONIC_READ_DISTANCE': 'ultrasonic sensor pin TRIG %1 ECHO %2 read distance %3'
        },
        'ru': {
            'ULTRASONIC_CATEGORY': 'Ultrasonic',
            'ULTRASONIC_READ_DISTANCE': 'ultrasonic sensor pin TRIG %1 ECHO %2 read distance %3'
        },
        'zh-cn': {
            'ULTRASONIC_CATEGORY': 'Ultrasonic',
            'ULTRASONIC_READ_DISTANCE': 'ultrasonic sensor pin TRIG %1 ECHO %2 read distance %3'
        },
        'zh-tw': {
            'ULTRASONIC_CATEGORY': 'Ultrasonic',
            'ULTRASONIC_READ_DISTANCE': 'ultrasonic sensor pin TRIG %1 ECHO %2 read distance %3'
        }
    }
};
